
spring:
  application:
    name: library-mgt-system
  datasource:
    url: jdbc:h2:mem:library
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=30s